# -*- coding: utf-8 -*-
"""github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhFq2RGnSQ3cLya1hfNP0kl3tItVbeAW
"""

print("Bilquis Haq")
print("My college major is Computer Science")