# -*- coding: utf-8 -*-
"""mypythonfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owNFKdFiJUByj5yB8aHxoNiCH0gqZAEN
"""

print("Bilquis Haq")
print("My college major is Computer Science")
print("I live in Franklin Park")